// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/txnutil/gc/gc_client.go

// Package gc is a generated GoMock package.
package gc

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	gc "github.com/tikv/pd/client/clients/gc"
)

// MockGCServiceClient is a mock of GCServiceClient interface.
type MockGCServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockGCServiceClientMockRecorder
}

// MockGCServiceClientMockRecorder is the mock recorder for MockGCServiceClient.
type MockGCServiceClientMockRecorder struct {
	mock *MockGCServiceClient
}

// NewMockGCServiceClient creates a new mock instance.
func NewMockGCServiceClient(ctrl *gomock.Controller) *MockGCServiceClient {
	mock := &MockGCServiceClient{ctrl: ctrl}
	mock.recorder = &MockGCServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGCServiceClient) EXPECT() *MockGCServiceClientMockRecorder {
	return m.recorder
}

// GetGCStatesClient mocks base method.
func (m *MockGCServiceClient) GetGCStatesClient(keyspaceID uint32) gc.GCStatesClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGCStatesClient", keyspaceID)
	ret0, _ := ret[0].(gc.GCStatesClient)
	return ret0
}

// GetGCStatesClient indicates an expected call of GetGCStatesClient.
func (mr *MockGCServiceClientMockRecorder) GetGCStatesClient(keyspaceID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGCStatesClient", reflect.TypeOf((*MockGCServiceClient)(nil).GetGCStatesClient), keyspaceID)
}

// UpdateServiceGCSafePoint mocks base method.
func (m *MockGCServiceClient) UpdateServiceGCSafePoint(ctx context.Context, serviceID string, ttl int64, safePoint uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceGCSafePoint", ctx, serviceID, ttl, safePoint)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateServiceGCSafePoint indicates an expected call of UpdateServiceGCSafePoint.
func (mr *MockGCServiceClientMockRecorder) UpdateServiceGCSafePoint(ctx, serviceID, ttl, safePoint interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceGCSafePoint", reflect.TypeOf((*MockGCServiceClient)(nil).UpdateServiceGCSafePoint), ctx, serviceID, ttl, safePoint)
}
