// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/redo/writer/writer.go

// Package writer is a generated GoMock package.
package writer

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	event "github.com/pingcap/ticdc/pkg/common/event"
)

// MockRedoEvent is a mock of RedoEvent interface.
type MockRedoEvent struct {
	ctrl     *gomock.Controller
	recorder *MockRedoEventMockRecorder
}

// MockRedoEventMockRecorder is the mock recorder for MockRedoEvent.
type MockRedoEventMockRecorder struct {
	mock *MockRedoEvent
}

// NewMockRedoEvent creates a new mock instance.
func NewMockRedoEvent(ctrl *gomock.Controller) *MockRedoEvent {
	mock := &MockRedoEvent{ctrl: ctrl}
	mock.recorder = &MockRedoEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedoEvent) EXPECT() *MockRedoEventMockRecorder {
	return m.recorder
}

// PostFlush mocks base method.
func (m *MockRedoEvent) PostFlush() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PostFlush")
}

// PostFlush indicates an expected call of PostFlush.
func (mr *MockRedoEventMockRecorder) PostFlush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostFlush", reflect.TypeOf((*MockRedoEvent)(nil).PostFlush))
}

// ToRedoLog mocks base method.
func (m *MockRedoEvent) ToRedoLog() *event.RedoLog {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToRedoLog")
	ret0, _ := ret[0].(*event.RedoLog)
	return ret0
}

// ToRedoLog indicates an expected call of ToRedoLog.
func (mr *MockRedoEventMockRecorder) ToRedoLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToRedoLog", reflect.TypeOf((*MockRedoEvent)(nil).ToRedoLog))
}

// MockRedoLogWriter is a mock of RedoLogWriter interface.
type MockRedoLogWriter struct {
	ctrl     *gomock.Controller
	recorder *MockRedoLogWriterMockRecorder
}

// MockRedoLogWriterMockRecorder is the mock recorder for MockRedoLogWriter.
type MockRedoLogWriterMockRecorder struct {
	mock *MockRedoLogWriter
}

// NewMockRedoLogWriter creates a new mock instance.
func NewMockRedoLogWriter(ctrl *gomock.Controller) *MockRedoLogWriter {
	mock := &MockRedoLogWriter{ctrl: ctrl}
	mock.recorder = &MockRedoLogWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedoLogWriter) EXPECT() *MockRedoLogWriterMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRedoLogWriter) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockRedoLogWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRedoLogWriter)(nil).Close))
}

// Run mocks base method.
func (m *MockRedoLogWriter) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockRedoLogWriterMockRecorder) Run(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockRedoLogWriter)(nil).Run), ctx)
}

// SetTableSchemaStore mocks base method.
func (m *MockRedoLogWriter) SetTableSchemaStore(arg0 *event.TableSchemaStore) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTableSchemaStore", arg0)
}

// SetTableSchemaStore indicates an expected call of SetTableSchemaStore.
func (mr *MockRedoLogWriterMockRecorder) SetTableSchemaStore(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTableSchemaStore", reflect.TypeOf((*MockRedoLogWriter)(nil).SetTableSchemaStore), arg0)
}

// WriteEvents mocks base method.
func (m *MockRedoLogWriter) WriteEvents(ctx context.Context, events ...RedoEvent) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range events {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WriteEvents", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteEvents indicates an expected call of WriteEvents.
func (mr *MockRedoLogWriterMockRecorder) WriteEvents(ctx interface{}, events ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, events...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteEvents", reflect.TypeOf((*MockRedoLogWriter)(nil).WriteEvents), varargs...)
}
